### ISSUE TITLE
.NET Outdated

### ISSUE THREAD

**Issue by alex-hedley** [alex-hedley/dotnet-dependencycheck#12]
https://github.com/dotnet-outdated/dotnet-outdated

`dotnet tool install --global dotnet-outdated-tool`

`dotnet outdated`

**Comment by alex-hedley** [comment]
- https://github.com/marketplace/actions/dotnet-outdated-install-and-update
  - https://github.com/stphnwlsh/dotnet-outdated-action

**Comment by alex-hedley** [comment]
```yml
    - name: Update
      id: update
      uses: stphnwlsh/dotnet-outdated-action@v2
      with:
        excludes: visualstudio
```
